# Generated by Django 3.0.4 on 2020-03-10 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=1024)),
            ],
        ),
    ]
