# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Python release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    env:
      FLAGSHIP_VERSION_NAME: ${GITHUB_REF/refs\/tags\//}
    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    if: contains(github.event.head_commit.message, '#ci-auto') == false && contains(github.event.head_commit.message, '#release-${GITHUB_REF/refs\/tags\//}') == false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Env
      run: |
          echo ::exportVariable name=FLAGSHIP_VERSION_NAME::${GITHUB_REF/refs\/tags\//}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        mkdir -p cache
    - name: Test with pytest
      run: |
        pytest
        
    - name: Coverage
      if: matrix.python-version == 3.7
      run: |
        pip install coverage
        coverage run --source=flagship -m pytest ./tests/
        coverage report -m
        
    - name: Upload coverage to Codecov
      if: matrix.python-version == 3.7
      uses: codecov/codecov-action@v2

    - name: Generate library
      if: matrix.python-version == 3.7
      run: |
          python3 -m pip install --user --upgrade setuptools wheel     
          python3 -m pip install --user --upgrade build
          rm -rf dist/
          python3 -m build --sdist --wheel --outdir dist/

    - name: Pypi publish
      if: matrix.python-version == 3.7
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist/